[package]
name = "waleedsamygd_minigrep"
version = "0.1.0"
authors = ["Waleed Samy <waleedsamygd@protonmail.com>"]
edition = "2018"
description = "search for string in a file"
license = "LGPL-2.1-only AND MIT AND BSD-2-Clause"

[dependencies]

[lib]
name="minigrep"
path="src/lib.rs"